# Generated by Django 5.2.6 on 2025-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_path_project_image_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='path',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='path',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='path',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('props', 'Props'), ('env', 'Environment'), ('vehicle', 'Vehicle'), ('fx', 'FX'), ('other', 'Other')], default='Generic', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
