# Generated by Django 5.2.6 on 2025-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asset_asset_type_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shots/'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
