# Generated by Django 5.2.6 on 2025-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shot_image_alter_sequence_name_alter_shot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_path',
            field=models.CharField(default='D:\\', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
