# Generated by Django 5.2.6 on 2025-09-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_base_path_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seq'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_path',
            field=models.CharField(default='D:\\\\', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shot'),
        ),
    ]
