# Generated by Django 5.2.6 on 2025-09-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sequence_image_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='core.project'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.project'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='core.sequence'),
        ),
    ]
