# Generated by Django 5.2.6 on 2025-09-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_artist_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('anim', 'anim'), ('env', 'env'), ('fx', 'fx'), ('layout', 'layout'), ('lgt', 'lgt'), ('mod', 'mod'), ('cfx', 'cfx'), ('ldev', 'ldev')], max_length=100),
        ),
    ]
