# Generated by Django 5.2.6 on 2025-09-19 16:01

import django.utils.timezone
from django.db import migrations, models


from django.db import migrations


def _populate_professional_emails(apps, schema_editor):
    Artist = apps.get_model('core', 'Artist')
    for artist in Artist.objects.all():
        if artist.username:
            artist.professional_email = f"{artist.username}@fx3x.com"
            artist.save(update_fields=['professional_email'])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_task_name_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists'),
        ),
        migrations.AddField(
            model_name='artist',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artist',
            name='private_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='artist',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='artist',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(_populate_professional_emails, _noop),
    ]
