# Generated by Django 5.2.6 on 2025-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_artist_country_artist_image_artist_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('vacation', 'On Vacation')], default='active', max_length=20),
        ),
    ]
