# Generated by Django 5.2.6 on 2025-09-28 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(base: str, existing: set[str], max_length: int, fallback: str) -> str:
    slug = slugify(base or "")[:max_length] or fallback
    candidate = slug
    counter = 2
    while candidate in existing or not candidate:
        suffix = f"-{counter}"
        candidate = f"{slug[:max_length - len(suffix)]}{suffix}" if len(slug) + len(suffix) > max_length else f"{slug}{suffix}" 
        candidate = candidate[:max_length]
        counter += 1
    existing.add(candidate)
    return candidate


def populate_initial_codes(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Asset = apps.get_model('core', 'Asset')
    Sequence = apps.get_model('core', 'Sequence')
    Shot = apps.get_model('core', 'Shot')

    # Projects should have globally unique codes
    existing_project_codes: set[str] = set(
        Project.objects.exclude(code__isnull=True).exclude(code__exact="").values_list('code', flat=True)
    )
    for project in Project.objects.all():
        if not project.code:
            project.code = _unique_slug(project.name, existing_project_codes, 32, 'proj')
            project.save(update_fields=['code'])

    # Cache project defaults
    project_defaults = {
        project.id: {
            'fps': project.default_fps,
            'width': project.resolution_width,
            'height': project.resolution_height,
            'color_space': project.color_space,
        }
        for project in Project.objects.all()
    }

    # Assets: ensure code/fps
    for project in Project.objects.all():
        existing_codes: set[str] = set(
            Asset.objects.filter(project=project)
            .exclude(code__isnull=True)
            .exclude(code__exact="")
            .values_list('code', flat=True)
        )
        for asset in Asset.objects.filter(project=project):
            updated_fields = []
            if not asset.code:
                asset.code = _unique_slug(asset.name, existing_codes, 64, 'asset')
                updated_fields.append('code')
            if asset.fps is None:
                asset.fps = project_defaults[project.id]['fps']
                updated_fields.append('fps')
            if updated_fields:
                asset.save(update_fields=updated_fields)

    # Sequences per project
    for project in Project.objects.all():
        existing_codes: set[str] = set(
            Sequence.objects.filter(project=project)
            .exclude(code__isnull=True)
            .exclude(code__exact="")
            .values_list('code', flat=True)
        )
        for sequence in Sequence.objects.filter(project=project):
            updated_fields = []
            if not sequence.code:
                sequence.code = _unique_slug(sequence.name, existing_codes, 32, 'seq')
                updated_fields.append('code')
            defaults = project_defaults.get(project.id, {})
            if sequence.fps is None:
                sequence.fps = defaults.get('fps', 24.0)
                updated_fields.append('fps')
            if sequence.resolution_width is None:
                sequence.resolution_width = defaults.get('width')
                updated_fields.append('resolution_width')
            if sequence.resolution_height is None:
                sequence.resolution_height = defaults.get('height')
                updated_fields.append('resolution_height')
            if not sequence.color_space:
                sequence.color_space = defaults.get('color_space', 'ACEScg')
                updated_fields.append('color_space')
            if updated_fields:
                sequence.save(update_fields=updated_fields)

    # Shots per sequence
    for sequence in Sequence.objects.all():
        existing_codes: set[str] = set(
            Shot.objects.filter(sequence=sequence)
            .exclude(code__isnull=True)
            .exclude(code__exact="")
            .values_list('code', flat=True)
        )
        defaults = project_defaults.get(sequence.project_id, {})
        for shot in Shot.objects.filter(sequence=sequence):
            updated_fields = []
            if not shot.code:
                shot.code = _unique_slug(shot.name, existing_codes, 64, 'shot')
                updated_fields.append('code')
            if shot.fps is None:
                shot.fps = sequence.fps or defaults.get('fps', 24.0)
                updated_fields.append('fps')
            if shot.resolution_width is None:
                shot.resolution_width = sequence.resolution_width or defaults.get('width')
                updated_fields.append('resolution_width')
            if shot.resolution_height is None:
                shot.resolution_height = sequence.resolution_height or defaults.get('height')
                updated_fields.append('resolution_height')
            if not shot.color_space:
                shot.color_space = sequence.color_space or defaults.get('color_space', 'ACEScg')
                updated_fields.append('color_space')
            if updated_fields:
                shot.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_asset_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Optional hex color for UI chips', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['project', 'code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['project', 'code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['sequence', 'code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'task_type', 'task_name']},
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='frame_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='frame_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pipeline_step',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('design', 'Design'), ('model', 'Model'), ('texture', 'Texture'), ('lookdev', 'Look Dev'), ('rigging', 'Rigging'), ('approved', 'Approved'), ('archived', 'Archived')], default='design', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='subtype',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='color_space',
            field=models.CharField(blank=True, default='ACEScg', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='default_fps',
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='resolution_height',
            field=models.PositiveIntegerField(default=858),
        ),
        migrations.AddField(
            model_name='project',
            name='resolution_width',
            field=models.PositiveIntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('bidding', 'Bidding'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sequence',
            name='color_space',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sequence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sequence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='fps',
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sequence',
            name='frame_end',
            field=models.IntegerField(default=1100),
        ),
        migrations.AddField(
            model_name='sequence',
            name='frame_start',
            field=models.IntegerField(default=1001),
        ),
        migrations.AddField(
            model_name='sequence',
            name='handles',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sequence',
            name='resolution_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='resolution_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='sequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shot',
            name='color_space',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shot',
            name='cut_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='cut_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='frame_end',
            field=models.IntegerField(default=1100),
        ),
        migrations.AddField(
            model_name='shot',
            name='frame_start',
            field=models.IntegerField(default=1001),
        ),
        migrations.AddField(
            model_name='shot',
            name='handles',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='shot',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='resolution_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='resolution_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shot',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('awaiting_client', 'Awaiting Client'), ('approved', 'Approved'), ('omit', 'Omit')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='shot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='bid_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Critical'), (20, 'High'), (50, 'Normal'), (80, 'Low')], default=50),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_initial_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('inactive', 'Inactive'), ('vacation', 'On Vacation')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('character', 'Character'), ('creature', 'Creature'), ('props', 'Props'), ('env', 'Environment'), ('vehicle', 'Vehicle'), ('fx', 'FX'), ('matte', 'Matte Painting'), ('rig', 'Rig'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('wip', 'Work In Progress'), ('internal_approved', 'Approved Internally'), ('client_approved', 'Approved by Client'), ('done', 'Done'), ('on_hold', 'On Hold')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('anim', 'Animation'), ('env', 'Environment'), ('fx', 'FX'), ('layout', 'Layout'), ('lgt', 'Lighting'), ('mod', 'Model'), ('cfx', 'Character FX'), ('ldev', 'LookDev'), ('comp', 'Compositing'), ('matte', 'Matte')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('project', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('sequence', 'code')},
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField()),
                ('software', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('iteration', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishes_created', to='core.artist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishes', to='core.project')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishes', to='core.task')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('target_content_type', 'target_object_id', 'task', 'version', 'iteration')},
            },
        ),
        migrations.CreateModel(
            name='PublishComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('component_type', models.CharField(choices=[('scene', 'Scene File'), ('cache', 'Cache'), ('preview', 'Preview'), ('image', 'Image'), ('data', 'Data')], default='scene', max_length=32)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('hash_md5', models.CharField(blank=True, max_length=64)),
                ('frame_start', models.IntegerField(blank=True, null=True)),
                ('frame_end', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.publish')),
            ],
            options={
                'ordering': ['publish', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetArtistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='core.artist')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_assignments', to='core.asset')),
            ],
            options={
                'unique_together': {('asset', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='ShotAssetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('archived', 'Archived')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_usages', to='core.asset')),
                ('publish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_usages', to='core.publish')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_usages', to='core.shot')),
            ],
            options={
                'unique_together': {('shot', 'asset', 'publish')},
            },
        ),
        migrations.CreateModel(
            name='ShotTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tags', to='core.shot')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tags', to='core.tag')),
            ],
            options={
                'unique_together': {('shot', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='SequenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_tags', to='core.sequence')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_tags', to='core.tag')),
            ],
            options={
                'unique_together': {('sequence', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='core.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='core.tag')),
            ],
            options={
                'unique_together': {('asset', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64)),
                ('responsibility', models.PositiveSmallIntegerField(default=100, help_text='Percent responsibility')),
                ('is_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.artist')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.task')),
            ],
            options={
                'unique_together': {('task', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='VersionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('dependency', 'Dependency'), ('input', 'Input'), ('upstream', 'Upstream'), ('rendered_from', 'Rendered From')], default='dependency', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='core.publish')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='core.publish')),
            ],
            options={
                'unique_together': {('source', 'target', 'link_type')},
            },
        ),
    ]
