# Generated by Django 5.0.4 on 2026-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_alter_asset_options_alter_sequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='asset_usd_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='item_usd_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='preview_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('deprecated', 'Deprecated'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
