# Generated by Django 5.0.4 on 2026-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publish_asset_usd_path_publish_item_usd_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='source_iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='source_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
