# Generated by Django 5.0.4 on 2026-02-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0015_publish_source_iteration_publish_source_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publish',
            unique_together={('target_content_type', 'target_object_id', 'task')},
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE core_publish "
                "SET source_version = COALESCE(source_version, version), "
                "    source_iteration = COALESCE(source_iteration, iteration);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='publish',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='version',
        ),
    ]
