# Generated by Django 5.0.4 on 2026-02-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_publish_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publish',
            unique_together=set(),
        ),
    ]
