# Generated by Django 5.0.4 on 2026-02-20 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_publish_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('fbx_name', models.CharField(max_length=128)),
                ('fbx_path', models.TextField()),
                ('textures_path', models.TextField()),
                ('asset_type', models.CharField(choices=[('character', 'Character'), ('prop', 'Prop')], max_length=16)),
                ('asset_category', models.CharField(choices=[('human', 'Human'), ('creature', 'Creature'), ('robot', 'Robot'), ('weapon', 'Weapon'), ('bag', 'Bag'), ('hair', 'Hair'), ('other', 'Other')], max_length=16)),
                ('skeleton_type', models.CharField(choices=[('mixamo', 'Mixamo'), ('none', 'None'), ('custom', 'Custom')], max_length=16)),
                ('units', models.CharField(choices=[('cm', 'cm'), ('m', 'm')], max_length=4)),
                ('scale_to_canonical', models.FloatField()),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], max_length=16)),
                ('age_group', models.CharField(blank=True, choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult'), ('elder', 'Elder'), ('unknown', 'Unknown')], max_length=16)),
                ('body_type', models.CharField(blank=True, choices=[('slim', 'Slim'), ('average', 'Average'), ('heavy', 'Heavy'), ('athletic', 'Athletic'), ('unknown', 'Unknown')], max_length=16)),
                ('role_tag', models.CharField(blank=True, choices=[('civilian', 'Civilian'), ('soldier', 'Soldier'), ('worker', 'Worker'), ('police', 'Police'), ('monster', 'Monster'), ('custom', 'Custom')], max_length=16)),
                ('role_text', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('wip', 'WIP'), ('approved', 'Approved')], default='wip', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=16)),
                ('qc_report_path', models.TextField(blank=True)),
                ('registered_by', models.CharField(blank=True, max_length=128)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.asset')),
            ],
            options={
                'ordering': ['-registered_at', '-version', '-id'],
                'unique_together': {('asset', 'version')},
            },
        ),
    ]
