# Generated by Django 5.0.4 on 2026-02-20 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assetversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_name', models.CharField(max_length=256)),
                ('texture_path', models.TextField()),
                ('file_ext', models.CharField(blank=True, max_length=16)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='core.assetversion')),
            ],
            options={
                'ordering': ['texture_name', 'id'],
            },
        ),
    ]
