# Generated by Django 5.0.4 on 2026-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assettexture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='deform_type',
            field=models.CharField(choices=[('skeleton_only', 'Skeleton Only'), ('skinned', 'Skinned')], default='skinned', max_length=24),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='pose_type',
            field=models.CharField(choices=[('t_pose', 'T-Pose'), ('animation', 'Animation')], default='t_pose', max_length=16),
        ),
    ]
